# Generated by Django 4.1 on 2023-09-16 05:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdraw',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 9, 16, 12, 3, 43, 881750)),
        ),
    ]
