# Generated by Django 4.1 on 2023-12-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_berat_deposit_total_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdraw',
            name='isApprove',
        ),
        migrations.AddField(
            model_name='redeemedprize',
            name='picture',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='token',
            field=models.CharField(default='PJEXFG', max_length=6, unique=True),
        ),
    ]
