# Generated by Django 4.1 on 2023-12-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_withdraw_isapprove_redeemedprize_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='username',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='waste_type',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='prize',
            name='picture',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='redeemedprize',
            name='desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='redeemedprize',
            name='picture',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='redeemedprize',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='balance',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='poin',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='token',
            field=models.CharField(default='TJDPAZ', max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='account_no',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='amount',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='method',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='provider',
            field=models.TextField(),
        ),
    ]
