# Generated by Django 4.1 on 2023-12-02 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_userdata_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='token',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
    ]
